#!/bin/bash

echo "======================================"
echo "上传代码到GitHub"
echo "======================================"
echo ""
echo "请在终端运行以下命令："
echo ""
echo "cd ~/Desktop/ai-showcase"
echo "git push -u origin main"
echo ""
echo "======================================"
echo "会提示输入："
echo "Username: potato123sdf"
echo "Password: 输入你的GitHub Personal Access Token"
echo ""
echo "如何获取Token："
echo "1. 访问 https://github.com/settings/tokens"
echo "2. 点击 Generate new token (classic)"
echo "3. 勾选 repo 权限"
echo "4. 生成并复制token"
echo "5. 粘贴到Password处"
echo "======================================"
