#!/bin/bash

echo "======================================"
echo "AI工具展示平台 - 启动指南"
echo "======================================"
echo ""
echo "由于npm缓存权限问题，请按以下步骤手动启动："
echo ""
echo "1. 修复npm权限（在终端运行）："
echo "   sudo chown -R \$(whoami) ~/.npm"
echo ""
echo "2. 安装前端依赖："
echo "   cd ~/Desktop/ai-showcase/client"
echo "   npm install"
echo ""
echo "3. 启动MongoDB（如果未运行）："
echo "   brew services start mongodb-community"
echo "   # 或者"
echo "   mongod --config /usr/local/etc/mongod.conf"
echo ""
echo "4. 启动后端服务器（新终端窗口）："
echo "   cd ~/Desktop/ai-showcase/server"
echo "   npm run dev"
echo ""
echo "5. 启动前端开发服务器（新终端窗口）："
echo "   cd ~/Desktop/ai-showcase/client"
echo "   npm run dev"
echo ""
echo "6. 访问应用："
echo "   http://localhost:3000"
echo ""
echo "======================================"
echo "功能说明："
echo "- 粒子背景交互效果"
echo "- 用户注册/登录（用户名+密码）"
echo "- 浏览10+个AI工具（包括Claudeyy镜像站）"
echo "- 点击卡片查看详细介绍"
echo "- 登录后可上传自己的AI工具"
echo "======================================"
